### ISSUE TITLE
legend floats when position set via bbox_to_anchor

### ISSUE THREAD

**Issue by story645** [matplotlib/ipympl#330] opened 2021-06-11 08:36 UTC
## Describe the issue
First noticed this on pan and zoom, but even on basic resize the legend moves all over the place when I set the location using 
```python
bbox_to_anchor=(1.45,1)
```
Here you can see the repositioning:

https://user-images.githubusercontent.com/1300499/121652954-30dbfe00-ca6a-11eb-98c3-35fc6c3a5063.mp4

where in the static version, the legend is firmly to the side:
![image](https://user-images.githubusercontent.com/1300499/121653155-5e28ac00-ca6a-11eb-9691-16b4dd0f4a95.png)

## Versions
I took the screencast with mpl 3.3.4, but am also observing it with 3.4.2
<details>

 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)]
ipympl version: 0.7.0
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : 5.0.3
ipython          : 7.22.0
ipykernel        : 5.5.5
jupyter client   : 6.1.12
jupyter lab      : 3.0.16
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
Config option `kernel_spec_manager_class` not recognized by `ListNBExtensionsApp`.
Known nbextensions:
  config dir: C:\Users\story\.jupyter\nbconfig
    notebook section
      jupyter-js-widgets/extension enabled
      - Validating: ok
  config dir: C:\Users\story\Anaconda3\envs\prop\etc\jupyter\nbconfig
    notebook section
      jupyter-matplotlib/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
[W 2021-06-11 04:11:00.742 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
JupyterLab v3.0.16
C:\Users\story\Anaconda3\envs\prop\share\jupyter\labextensions
        jupyter-matplotlib v0.9.0 enabled ok
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled ok (python, jupyterlab_widgets)
</details>

**Comment by ianhi** [comment] 2021-06-14 17:55
Can you post code to reproduce?

Also can you try this in a non-notebook backend (or with nbagg). I think all the logic for placing the legend happens in core maptlotlib and don't think that ipympl is where this should be fixed.

**Comment by story645** [comment] 2021-06-14 19:13
So that code is a mess, but pinning down to a minimal example:
```python
fig, ax = plt.subplots(figsize=(6,10))
l, = ax.plot([1,2,3], [1,2,3], label="hello")
ax.legend(bbox_to_anchor=(1, 1))
```
It's the interaction between figsize and bbox_to_anchor, and the floating doesn't happen in TkAgg. If I don't set a figsize, then the legend stays in the right place, but is cut off both in ipympl and TkAgg, so that's a GUI interface bug. 
![image](https://user-images.githubusercontent.com/1300499/121945092-64947d80-cd21-11eb-9962-2e7c3dbb470a.png)

**Comment by ianhi** [comment] 2021-06-14 19:18
Does this happen with `nbagg` as well?

**Comment by story645** [comment] 2021-06-14 19:31
Yes, so should I post this issue back to Matplotlib?

**Comment by ianhi** [comment] 2021-06-14 19:34
> Yes, so should I post this issue back to Matplotlib?

yup that means it probably an issue with webaggcore. or perhaps something in the shared code of nbagg and ipympl in which case it will also need to be fixed there as well.

FWIW I'm still a little confused as to what the core bug is. The legend getting cut off I see, but I'm not sure what you mean by `floating` and I don't seem to be able to reproduce it with your minimal example.

**Comment by story645** [comment] 2021-06-14 19:49
So this is kinda contrived, but the legend starts out inside the axes and moves outside it when I stretch the frame.
https://user-images.githubusercontent.com/1300499/121950713-fdc69280-cd27-11eb-9320-7ea8df3f8476.mp4

**Comment by jklymak** [comment] 2021-06-14 20:25
You are getting floating behaviour because the default location in "best".  
```python
fig, ax = plt.subplots(figsize=(6,10), constrained_layout=True)
l, = ax.plot([1,2,3], [1,2,3], label="hello")
ax.legend(loc='upper left', bbox_to_anchor=(1, 1))
plt.show()
```

will always put the legend to the right, and if you use constrained_layout, it will make room for the legend w/o floating behaviour (so long as the legend is in axes co-ordinates and does not become too huge)

**Comment by story645** [comment] 2021-06-14 20:28
I'm surprised that bbox_to_anchor doesn't supercede loc.

**Comment by jklymak** [comment] 2021-06-14 20:30
It needs to know how to align the legend relative to that bbox so it still tries all the alignments to find one that doesn't cover data.

**Comment by ianhi** [comment] 2021-06-15 14:42
So is the conclusion here is that this is not an ipympl bug but rather a natural consequence of the layout engine? With your example I also see the floating with qt5 backend.

**Comment by jklymak** [comment] 2021-06-15 14:48
This is normal and expected matplotlib behaviour.

**Comment by ianhi** [comment] 2021-06-15 15:22
Let's close this then

**Closed by ianhi** 2021-06-15 15:22 UTC
