### ISSUE TITLE
"Error displaying widget: model not found" again

### ISSUE THREAD

**Issue by asteppke** [matplotlib/ipympl#323] opened 2021-05-20 16:20 UTC
After an update of Jupyterlab I cannot use ipympl anymore as the minimal example

````python
%matplotlib widget
from matplotlib import pyplot as plt

fig, ax = plt.subplots()
````
only shows "Error displaying widget: model not found".

Unfortunately something in the Jupyter/matplotlib/ipympl machinery seems very fragile so that this is easily triggered. In the past a simple re-install of ipympl helped but this does not seem to work here at the moment. 

My environment looks like
````
 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:23) [MSC v.1916 64 bit (AMD64)]
ipympl version: 0.7.0
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : not installed
ipython          : 7.23.1
ipykernel        : 5.5.5
jupyter client   : 6.1.12
jupyter lab      : 3.0.15
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
Config option `kernel_spec_manager_class` not recognized by `ListNBExtensionsApp`.
Known nbextensions:
  config dir: C:\tools\miniconda3\envs\jupyter\etc\jupyter\nbconfig
    notebook section
      jupyter-matplotlib/extension enabled
      - Validating: ok
      jupytext/index enabled
      - Validating: ok
      nbdime/index enabled
      - Validating: ok
      voila/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
[W 2021-05-20 18:11:49.703 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
JupyterLab v3.0.15
C:\tools\miniconda3\envs\jupyter\share\jupyter\labextensions
        jupyter-matplotlib v0.9.0 enabled ok
        jupyterlab-jupytext v1.3.1 enabled ok (python, jupytext)
        nbdime-jupyterlab v2.1.0 enabled ok
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled ok (python, jupyterlab_widgets)
        @ryantam626/jupyterlab_code_formatter v1.4.10 enabled ok (python, jupyterlab-code-formatter)
        @voila-dashboards/jupyterlab-preview v2.0.2 enabled ok (python, voila)
````
Chrome complains in the Javascript console that `Uncaught (in promise) Error: Module jupyter-matplotlib, semver range ^0.9.0 is not registered as a widget module` and earlier errors such as `Plugin 'matplotlib-jupyter:main' failed to activate.`

When using a completely fresh conda environment ipympl has always worked here, but something breaks when updating parts of the environment and then I do not see what is broken and an simple reinstall (`conda uninstall ipympl`, `conda install -c conda-forge ipympl`) works but the error message remains and the plot cannot be displayed.

Any hint how to diagnose or prevent this from happening would be appreciated.

**Comment by ianhi** [comment] 2021-05-20 16:54
> When using a completely fresh conda environment ipympl has always worked here, but something breaks when updating parts of the environment and then I do not see what is broken and an simple reinstall 

Do you mean that at the start it works and eventually gets broken as you install more things?

Can you confirm whether this works:

```bash
conda create -n ipympl-test -c conda-forge jupyterlab ipympl
conda activate ipympl-test
jupyter lab
```

**Comment by asteppke** [comment] 2021-05-20 17:27
> Do you mean that at the start it works and eventually gets broken as you install more things?

Exactly. Unfortunately I do not know exactly at which point it breaks because I don't manually test ipympl after updating. 

````
conda create -n ipympl-test -c conda-forge jupyterlab ipympl
conda activate ipympl-test
jupyter lab
````
leads to a working environment. So in this clean case everything is fine.

**Comment by asteppke** [comment] 2021-05-21 17:10
Before getting to the bottom of this a uninstall and reinstall of all jupyter related packages, followed by a reinstall of ipympl helped. 

The underlying problem somehow remains, all diagnostic tools such as `jupyter labextension list` report a working environment and only when the actual notebook is run and a figure is created it fails. Is there a way to test the machinery, for example post-installation via the command line?

**Comment by neurobot01** [comment] 2021-07-02 05:33
Having similar issues. Relevant environment details:

```
python version 3.7.3 (default, Aug  4 2020, 19:30:55) 
[Clang 11.0.3 (clang-1103.0.32.62)]
ipympl version: 0.7.0
jupyter core     : 4.7.1
jupyter-notebook : 6.4.0
qtconsole        : 5.1.1
ipython          : 7.25.0
ipykernel        : 6.0.0
jupyter client   : 6.1.12
jupyter lab      : 3.0.16
nbconvert        : 6.1.0
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5

Known nbextensions:
  config dir: /Users/XXX/.jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      plotlywidget/extension  enabled 
      - Validating: OK
JupyterLab v3.0.16
Other labextensions (built into JupyterLab)
   app dir: /Users/XXX/Library/Python/3.7/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled OK
        jupyter-matplotlib v0.9.0 enabled OK

matplotlib          3.4.2
matplotlib-inline   0.1.2
pip                 21.1.2
plotly              4.0.0
```

From the oft-referenced table, it looks like ipympl, jupyter-matplotlib, JupyterLab, and Matplotlib should all be compatible. Everything installed via pip, without any Docker or venv or other intermediaries.

The code that fails comes from [MRIQception](https://github.com/elizabethbeard/mriqception), in particular, the plotting from tools/figs.py, with the "model not found" error accompanied by "Module plotlywidget, semver range ^1.0.0 is not registered as a widget module" errors in the java console, along with two other classes of error ("Error: Could not create a model." and "Exception opening new comm").

I've checked and at a minimum, when checking the version from inside this notebook, the matplotlib and ipympl versions line up with the output from terminal copied above. I've also restarted the kernel, restarted JupyterLab, restarted the computer (iMac running macOS 10.15.6), cleared the browser cache, and reloaded the page, all with the same exact errors. All the earlier widgets (the RadioButtons, FloatSlider, and SelectMultiple) work without issue each time.

Happy to run any other checks that would be helpful in debugging, assuming I'm not missing something obvious.

**Comment by NA-Dev** [comment] 2021-08-16 03:17
Same is happening for me when I try to install ipympl to get animated plots in the latest Jupyter lab. Granted I don't know how this is all supposed to work and may just be doing it wrong.

**Comment by martinRenou** [comment] 2021-08-16 07:51
@NA-Dev could you open an issue for your case? When opening an issue it will ask you to provide some information that will help us debug

**Comment by martinRenou** [comment] 2021-08-16 07:51
Closing this issue.

**Closed by martinRenou** 2021-08-16 07:51 UTC

**Comment by asteppke** [comment] 2021-08-16 09:03
@martinRenou: I think the problem is not completely resolved, as the other reporters have at least identical error messages. Is this addressed somewhere that we overlooked?

My current hunch, and I would be happy to assist at a complete reproduction of this bug, is that the installation/build process is not fully working under certain circumstances. I never observed this behavior in a fresh environment but only if ipympl is part of the build, update or installation of an already existing JupyterLab environment. As if some leftover breaks the process and then does not recover, even when trying the installation again. This behavior, the lack of error messages, paired with the information from `jupyter labextension list` that everything is in perfect order creates a barrier for many users.

**Comment by martinRenou** [comment] 2021-08-16 09:08
This kind of behavior can happen if you install another widget extension that is not JupyterLab 3 compatible, it can break ipympl. 

Could you provide `jupyter labextension list` for the case when it doesn't work?

**Comment by asteppke** [comment] 2021-08-16 09:28
Thank you for picking this up! One configuration where it does not work shows this output from my earlier comment:

````
Config option `kernel_spec_manager_class` not recognized by `ListLabExtensionsApp`.
[W 2021-05-20 18:11:49.703 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
JupyterLab v3.0.15
C:\tools\miniconda3\envs\jupyter\share\jupyter\labextensions
        jupyter-matplotlib v0.9.0 enabled ok
        jupyterlab-jupytext v1.3.1 enabled ok (python, jupytext)
        nbdime-jupyterlab v2.1.0 enabled ok
        @jupyter-widgets/jupyterlab-manager v3.0.0 enabled ok (python, jupyterlab_widgets)
        @ryantam626/jupyterlab_code_formatter v1.4.10 enabled ok (python, jupyterlab-code-formatter)
        @voila-dashboards/jupyterlab-preview v2.0.2 enabled ok (python, voila)
````

So on the surface it looks like this should work but in that environment ipympl failed to run. Just by comparison with other configurations/machines it does not look like that it is specific to this particular set of extensions. neurobot01 above could trace it to an interaction with plotly. 

If ipympl is broken by the installation of other extensions and a reinstallation of ipympl does not help is there a general way how to recover from this situation or get some diagnostics?

**Comment by martinRenou** [comment] 2021-08-16 09:37
> If ipympl is broken by the installation of other extensions and a reinstallation of ipympl does not help is there a general way how to recover from this situation or get some diagnostics?

Would you be able to open the console from the developer tools of your browser and show us the JavaScript errors?

**Comment by asteppke** [comment] 2021-08-16 09:45
When this error occurred Chrome complains in the Javascript console that `Uncaught (in promise) Error: Module jupyter-matplotlib`, `semver range ^0.9.0 is not registered as a widget module` and earlier errors such as `Plugin 'matplotlib-jupyter:main' failed to activate`. 

I updated my jupyterlab installation multiple times since then and currently it is running again without issues. Unfortunately I don't have a disc snapshot from that exact moment. What would be possible that I create a snapshot as soon as this creeps up again.

**Comment by martinRenou** [comment] 2021-08-16 09:46
👍🏽

**Comment by gioxc88** [comment] 2021-09-13 16:56
I am getting the same error

**Comment by coderdoufu** [comment] 2021-12-12 07:29
I am having the same problem. After running `jupyter labextension list` I received the following output:

```
JupyterLab v3.2.5
/home/studio-lab-user/.conda/envs/default/share/jupyter/labextensions
        jupyter-matplotlib v0.10.2 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)
        @jupyter-widgets/jupyterlab-sidecar v0.6.1 enabled OK (python, sidecar)
```

**Comment by tritas** [comment] 2022-01-12 10:55
Could we please re-open the issue? 

Also seeing the same Javascript error in the console
``Error: Module jupyter-matplotlib, semver range ^0.10.4 is not registered as a widget module``.

Lab extension versions similar to above:
```
JupyterLab v3.2.5
/.../share/jupyter/labextensions
        jupyter-matplotlib v0.10.4 enabled OK
        @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)
```

And package versions:
```
ipympl                    0.8.5              pyhd8ed1ab_0    conda-forge
ipywidgets                7.6.5              pyhd3eb1b0_1  
jupyterlab                3.2.5              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
matplotlib                3.5.1            py39hf3d152e_0    conda-forge
```

**Comment by asteppke** [comment] 2022-01-12 11:01
@tritas: Could you please create a new conda environment from scratch and install only jupyterlab, ipympl and the respective dependencies? My hunch is still that the error then goes away which might help to narrow this down.

**Comment by stoffprof** [comment] 2022-01-13 21:17
I came here because I was getting the same error.

I can confirm that in a new environment, as suggested by @asteppke above, the error goes away. I added scipy to the environment as well and that didn't cause problems.

Here is the output of `jupyter labextension list` in the environment without problems:

> JupyterLab v3.2.8
> /Users/nstoffma/opt/anaconda3/envs/ipympl-test/share/jupyter/labextensions
>         jupyter-matplotlib v0.10.4 enabled OK
>         @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)
> 

and here it is in my environment that was throwing an error:

> JupyterLab v3.2.1
> /Users/nstoffma/opt/anaconda3/envs/data/share/jupyter/labextensions
>         jupyterlab-jupytext v1.3.4 enabled OK (python, jupytext)
>         nbdime-jupyterlab v2.1.1 enabled OK
>         jupyter-matplotlib v0.10.4 enabled OK
>         @jupyter-widgets/jupyterlab-manager v3.0.1 enabled OK (python, jupyterlab_widgets)

**Comment by martinRenou** [comment] 2022-01-14 09:54
As I said above:

> This kind of behavior can happen if you install another widget extension that is not JupyterLab 3 compatible, it can break ipympl.

Maybe `nbdime-jupyterlab` or `jupyterlab-jupytext` is responsible here?

**Comment by martinRenou** [comment] 2022-01-14 09:55
Maybe `nbdime-jupyterlab` or `jupyterlab-jupytext` could be responsible? If they ship widget extensions that are not JupyterLab 3 compatible it's possible they break the setup, but I'm not sure.

**Comment by prajwel** [comment] 2022-03-26 15:17
Hi @martinRenou,  I have been checking new updates to ipympl to see if this error goes away, but so far only the ipympl==0.8.0 works for me.

**Comment by ianhi** [comment] 2022-03-27 01:52
Hi @prajwel can you please open a new issue and fill out the issue template (e.g. jupyterlab version etc) that will make it easier to debug thanks!
